# LSC For now
NOGCCERROR:= yes

LIB=    exec

CPPFLAGS+=      -I${.CURDIR}/include -I${.CURDIR}/..
CPPFLAGS+=      -I${.CURDIR}/arch/${ARCHSUBDIR}

CPPFLAGS+=      -I${.CURDIR}/include -I${.CURDIR}/..
CPPFLAGS+=      -I${.CURDIR}/arch/${ARCHSUBDIR}

INCSDIR= /usr/include 

SUBDIR=unistd
.include <bsd.subdir.mk>

.include <bsd.lib.mk>
