# LSC For now
NOGCCERROR:= yes

LIB=    unistd
INCS=   charclass.h
SRCS=   alarm.c  exec.c fnmatch.c syslog.c system.c time.c

INCSDIR= /usr/include ${.CURDIR}/../include ${.CURDIR}/../

.include <bsd.lib.mk>

